server:
  port: 8080

chatApp-authorization:
    url: ${CHAT_APP_AUTHORIZATION_URL:http://localhost:9090}

spring:
  application: gateway
  kafka:
    bootstrap-servers: localhost:9082
    consumer:
      group-id: messenger-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  sql:
    init:
      mode: always
  redis:
    host: localhost
    port: 6379
    password:
    database: 0