server:
  port: 8080

chatApp-authorization:
  url: ${CHAT_APP_AUTHORIZATION_URL:http://localhost:9090}

spring:
  application: gateway
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: messenger-group
      auto-offset-reset: earliest

  sql:
    init:
      mode: always
  redis:
    host: localhost
    port: 6379
    password:
    database: 0