server:
  port: 9070

spring:
  application:
    name: messenger

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: messenger-group
      auto-offset-reset: earliest

  datasource:
    url: jdbc:postgresql://localhost:6432/chatApp
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true